//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Resources;

namespace nanoFramework.Telegram.Bot.Tests
{
    
    internal partial class Res
    {
        private static ResourceManager manager;
        internal static ResourceManager ResourceManager
        {
            get
            {
                if ((Res.manager == null))
                {
                    Res.manager = new ResourceManager("nanoFramework.Telegram.Bot.Tests.Res", typeof(Res).Assembly);
                }
                return Res.manager;
            }
        }
        internal static string GetString(Res.StringResources id)
        {
            return ((string)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [SerializableAttribute()]
        internal enum StringResources : short
        {
            GetUpdatesOneMessageAndOneCallbackResponse = -9628,
            GetUpdatesOneCallbackResponse = -9122,
            SendMessageResponse = 9488,
            BaseResponseOk = 10185,
            GetUpdatesOneMessageResponse = 15556,
            BaseResponse401 = 16931,
            GetMeResponse = 23465,
        }
    }
}
